### ISSUE TITLE
Arbitrage mispricing subgraph issue

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#356]

**Comment by OlaStenberg** [comment]
Fixed on https://github.com/sushiswap/subgraphs/tree/feature/volume-arb-fix

Will NOT merge that into master since MEV attacks are 99% happening on ethereum, seems unnecessary to add that logic to every network. However, this fix needs to be applied to trident if we launch that on mainnet. Perhaps we can add it to the network configuration, `trident.features.mevProtection: false`, make it a global constant and just ignore the logic based on that..

Also dumping some thoughts on the `Swap` entity that we could improve
## swap.amountUSD 
The field `amountUSD` is correct for the wrong reason, it's less obvious when it's a regular trade. Example:
User swaps 10 USDC for 10 DAI.
The `amountUSD` will be 10 usd, but the way it's calculated is `amountIn` + `amountOut` / 2

And when there's a sandwich attack and an MEV bot makes the pair imbalanced to squeeze the user, the trade could look something like this:
MEV BOT swaps 100 USDC for 10 DAI.
`amountUSD` will now be 55, because of the calculation shown in the previous example..

Which makes me question what the goal with amountUSD was to begin with, why not just have `amountInUsd` and `amountOutUsd`.. Or just track the `amountOutUsd` as `amountUSD`

## swap.amountIn/Out VS. amount0In,  amount1In,  amount0Out,  amount1Out
We decided that amountIn and amountOut was better to save to avoid having to deal with checking the fields in the application, but as it turns out there are swaps with two amounts in on legacy. 
We previously assumed, if amount0In has a value, amount1Out does too (or the other way around, 1In, 0Out) which has led to a few edge cases where `amountOut` is now 0. Not exactly sure how we fix this and make it compatible with trident as there is no 0/1 on there.
